### ISSUE TITLE
CoachMark.dismiss causes a crash if parent activity has been destroyed.

### ISSUE THREAD

**Issue by DerekARodrigues** [TouchType/CornedBeef#19]
I'm seeing the following crash from a CoachMark dismiss:

`Fatal Exception: java.lang.IllegalArgumentException: View=android.widget.PopupWindow$PopupViewContainer{41d708f0 V.E..... ......ID 0,0-800,1191} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:370)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:299)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:84)
       at android.widget.PopupWindow.dismiss(PopupWindow.java:1364)
       at com.swiftkey.cornedbeef.CoachMark.dismiss(Unknown Source)
       at com.swiftkey.cornedbeef.CoachMark$1.run(Unknown Source)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`

From what I've read, this can occur if a dialog is dismissed after the parent activity has already been destroyed. In my case, I am auto-dismissing a CoachMark from an async task so it is entirely possible this could happen.

The following SO post has some suggestions on how to resolve this:
http://stackoverflow.com/questions/2745061/java-lang-illegalargumentexception-view-not-attached-to-window-manager

**Comment by ojj11** [comment]
Thanks for all this information - this is fixed in master now :)
